on:
    push:
        paths:
            - "**.php"
    pull_request:
        paths:
            - "**.php"

name: build

jobs:
    tests:
        name: PHP ${{ matrix.php }}-${{ matrix.os }}
        env:
            extensions: json, zip

        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os:
                    - ubuntu-latest

                php:
                    - "7.2"
                    - "7.3"
                    - "7.4"
                    - "8.0"

        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: setup cache for PHP extensions
              id: cache-env-php
              uses: shivammathur/cache-extensions@v1
              with:
                  php-version: ${{ matrix.php }}
                  extensions: ${{ env.extensions }}
                  key: cache-php${{ matrix.php }}-extensions

            - name: cache PHP extensions
              uses: actions/cache@v4
              with:
                  path: ${{ steps.cache-env-php.outputs.dir }}
                  key: ${{ steps.cache-env-php.outputs.key }}
                  restore-keys: ${{ steps.cache-env-php.outputs.key }}

            - name: install php and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: ${{ env.extensions }}
                  ini-values: date.timezone='UTC'
                  coverage: xdebug
                  tools: composer:v2, pecl

            - name: find composer cache directory (linux)
              run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

            - name: install cache dependencies with composer
              uses: actions/cache@v4
              with:
                  path: ${{ env.COMPOSER_CACHE_DIR }}
                  key: php${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: |
                      php${{ matrix.php }}-composer-

            - name: update dependencies with composer
              run: composer update --no-interaction --no-progress --optimize-autoloader --ansi

            - name: run tests with phpunit 5.7.27
              run: ./vendor/bin/phpunit tests
